/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ConvertLibContract } from "./ConvertLib";
import { MetaCoinContract } from "./MetaCoin";
import { MigrationsContract } from "./Migrations";

declare global {
  namespace Truffle {
    interface Artifacts {
      require(name: "ConvertLib"): ConvertLibContract;
      require(name: "MetaCoin"): MetaCoinContract;
      require(name: "Migrations"): MigrationsContract;
    }
  }
}

export { ConvertLibContract, ConvertLibInstance } from "./ConvertLib";
export { MetaCoinContract, MetaCoinInstance } from "./MetaCoin";
export { MigrationsContract, MigrationsInstance } from "./Migrations";
